#!/usr/bin/env bun

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readPlaybookGraphPackage } from "../packages/core/src/playbook-graph-package.js";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const builtInsRoot = join(repoRoot, "packages/core/src/builtin-graph-playbooks");
const outputPath = join(repoRoot, "packages/core/src/builtin-graph-playbook-bundles.generated.ts");

const roots = readdirSync(builtInsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => join(builtInsRoot, entry.name));

const bundles: Record<string, { sourceFiles: Record<string, string> }> = {};

for (const root of roots) {
  const packageFiles = await readPlaybookGraphPackage(root);
  bundles[packageFiles.manifest.id] = { sourceFiles: packageFiles.sourceFiles };
}

const body = `// Generated by scripts/generate-builtin-graph-playbook-bundles.ts. Do not edit by hand.

export const BUILTIN_GRAPH_PLAYBOOK_SOURCE_BUNDLES = ${JSON.stringify(bundles, null, 2)} as const satisfies Record<
  string,
  { sourceFiles: Record<string, string> }
>;
`;

writeFileSync(outputPath, body);
console.log(`[generate-builtin-graph-playbook-bundles] wrote ${outputPath}`);
